### ISSUE TITLE
刷squashfs固件，重启后恢复出厂设置

### ISSUE THREAD

**Issue by ghost** [RikudouPatrickstar/R2S-OpenWrt#1]
重启之后就恢复出厂设置，配置信息全部丢失。是不是跟overlay有关系。

**Comment by RikudouPatrickstar** [comment]
是的，R2S比较挑卡，很老的问题了，各个固件都有。
解决方案：
1. 换张 MLC 的 TF 卡
2. 拔卡刷，刷之前把卡上面前面 1GB 的空间拿东西塞满。第一次启动后执行 firstboot -y && reboot
