### ISSUE TITLE
你好 最近这几版没有恢复出厂设置按钮了

### ISSUE THREAD

**Issue by Jiahao369** [RikudouPatrickstar/R2S-OpenWrt#2]
下个版本能否添加上 万分感谢

**Comment by RikudouPatrickstar** [comment]
你是指 web 控制台没有“恢复出厂”按钮，还是戳 r2s 的物理按钮无效？

前者的话，我没有砍掉啊；后者的话只有 squashfs 的固件支持，你是不是下错成 ext4 格式的了？

**Comment by Jiahao369** [comment]
web 控制台没有“恢复出厂”按钮, squashfs 也没有。刚刚刷了新版本 现在有了  谢谢大佬更新 固件很好用
