### ISSUE TITLE
Submenu "software not show" on system

### ISSUE THREAD

**Issue by adibindrianto** [RikudouPatrickstar/R2S-OpenWrt#4]
How to fix it submenu "software" not show? can you tell me please

**Comment by RikudouPatrickstar** [comment]
Delete this line of code:
https://github.com/RikudouPatrickstar/R2S-OpenWrt/blob/0c2d79a47bba137fde25117a804b5ef837c20334/SCRIPTS/my_prepare_package.sh#L27

 and then recompile this project

**Comment by RikudouPatrickstar** [comment]
I don't like this submenu so I deleted it.

**Comment by adibindrianto** [comment]
thank you
